# Generated by Django 5.0 on 2023-12-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_ourservices"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img", models.ImageField(upload_to="media", verbose_name="Image")),
                ("title", models.CharField(max_length=50, verbose_name="Title")),
                ("text", models.CharField(max_length=50, verbose_name="Text")),
            ],
            options={
                "verbose_name": "Gallery",
                "verbose_name_plural": "Galleries",
            },
        ),
    ]
