# Generated by Django 5.0 on 2023-12-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_gallery"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallery",
            name="img_display",
            field=models.ImageField(
                null=True, upload_to="media", verbose_name="Large Image"
            ),
        ),
    ]
