# Generated by Django 5.0 on 2023-12-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_contactus"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeBG",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bg1",
                    models.ImageField(
                        upload_to="media", verbose_name="Back Ground Image"
                    ),
                ),
                (
                    "bg2",
                    models.ImageField(
                        upload_to="media", verbose_name="Back Ground Image"
                    ),
                ),
                (
                    "bg3",
                    models.ImageField(
                        upload_to="media", verbose_name="Back Ground Image"
                    ),
                ),
                (
                    "bg4",
                    models.ImageField(
                        upload_to="media", verbose_name="Back Ground Image"
                    ),
                ),
            ],
            options={
                "verbose_name": "Home BG",
                "verbose_name_plural": "Home BG",
            },
        ),
    ]
