# Generated by Django 5.0 on 2023-12-09 15:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_aboutus"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aboutus",
            options={"verbose_name": "About Us", "verbose_name_plural": "About Us"},
        ),
    ]
