# Generated by Django 5.0 on 2023-12-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_alter_aboutus_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Icons",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("icon", models.CharField(max_length=50)),
                ("text", models.TextField()),
            ],
            options={
                "verbose_name": "Icons",
                "verbose_name_plural": "Icons",
            },
        ),
    ]
